CREATE TABLE PERSON(
SSN NUMBER(3) NOT NULL,
NAME VARCHAR2(15),
AGE NUMBER(3),
JOBTYPE VARCHAR2(15),
PRIMARY KEY(SSN));

CREATE TABLE CENTRE(
CNTID NUMBER(3) NOT NULL,
CNTNAME VARCHAR2(15),
CITY VARCHAR2(15),
BUDGET NUMBER(10,2),
MANAGERID NUMBER(3),
PRIMARY KEY(CNTID),
FOREIGN KEY(MANAGERID) REFERENCES PERSON(SSN));

CREATE TABLE PCOMPANY(
CNAME VARCHAR2(20) NOT NULL,
CPHONE VARCHAR2(15),
PRIMARY KEY(CNAME));

CREATE TABLE VACCINE(
VNAME VARCHAR2(20) NOT NULL,
FORMULA VARCHAR2(15),
MADEBY VARCHAR2(20),
PRIMARY KEY(VNAME),
FOREIGN KEY(MADEBY) REFERENCES PCOMPANY(CNAME));

CREATE TABLE SELLS(
VNAME VARCHAR2(20) NOT NULL,
CNAME VARCHAR2(20) NOT NULL,
PRICE NUMBER(6,2),
PRIMARY KEY(VNAME, CNAME),
FOREIGN KEY(VNAME) REFERENCES VACCINE(VNAME),
FOREIGN KEY(CNAME) REFERENCES PCOMPANY(CNAME));

CREATE TABLE VACCINATES(
SSN NUMBER(3) NOT NULL,
CNTID NUMBER(3) NOT NULL,
PRIMARY KEY(SSN, CNTID),
FOREIGN KEY(SSN) REFERENCES PERSON(SSN),
FOREIGN KEY(CNTID) REFERENCES CENTRE(CNTID));

CREATE TABLE ADMINISTERS(
SSN NUMBER(3) NOT NULL,
CNTID NUMBER(3) NOT NULL,
VNAME VARCHAR2(20) NOT NULL,
VACDATE DATE,
DOSE NUMBER(3),
VACTIME NUMBER(6,2),
PRIMARY KEY(SSN, CNTID, VNAME),
FOREIGN KEY(SSN) REFERENCES PERSON(SSN),
FOREIGN KEY(CNTID) REFERENCES CENTRE(CNTID),
FOREIGN KEY(VNAME) REFERENCES VACCINE(VNAME));

