
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 11 19:42:33 EST 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int READ = 12;
  public static final int ELSE = 18;
  public static final int SEMICOLON = 7;
  public static final int RPAREN = 4;
  public static final int END = 15;
  public static final int RETURN = 10;
  public static final int IF = 11;
  public static final int LPAREN = 3;
  public static final int WRITE = 13;
  public static final int ID = 6;
  public static final int BEGIN = 14;
  public static final int TYPE = 9;
  public static final int COMMA = 19;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int MAIN = 8;
  public static final int error = 1;
  public static final int ASSIGN = 5;
  public static final int ARITH = 2;
  public static final int QSTRING = 17;
  public static final int BOOL = 16;
  public static final int BOOLVAL = 21;
}

